apiVersion: v1
kind: Secret
metadata:
  name: juicefs-secret
type: Opaque
data:
  name: <base64-encoded-name>
  metaurl: <base64-encoded-redis-url>
  storage: <base64-encoded-storage-type>
  bucket: <base64-encoded-bucket-url>
  access-key: <base64-encoded-access-key>
  secret-key: <base64-encoded-secret-key>
