apiVersion: v1
kind: Pod
metadata:
  name: juicefs-test
spec:
  containers:
  - name: test
    image: busybox
    command: [ "sleep", "3600" ]
    volumeMounts:
    - mountPath: "/data"
      name: juicefs-volume
  volumes:
  - name: juicefs-volume
    persistentVolumeClaim:
      claimName: juicefs-pvc