apiVersion: v1
kind: Pod
metadata:
  name: check-data
spec:
  containers:
  - name: check
    image: python:3.9-slim
    command: 
    - "bash"
    - "-c"
    - |
      echo "Checking JuiceFS mount..."
      ls -la /mnt/jfs/
      echo "Checking datasets directory..."
      ls -la /mnt/jfs/datasets/ || echo "datasets directory not found"
    volumeMounts:
    - name: juicefs-volume
      mountPath: /mnt/jfs
  volumes:
  - name: juicefs-volume
    persistentVolumeClaim:
      claimName: juicefs-pvc
  restartPolicy: Never 